[package]
name        = "llm_node"
version     = "0.1.0"
edition     = "2021"
authors     = ["Marcus Schlieper <mschlieper@ylook.de>"]


[dependencies]
candle = { git = "https://github.com/huggingface/candle", package = "candle-core", default-features = false }
candle_nn = { git = "https://github.com/huggingface/candle", package = "candle-nn", default-features = false }
candle_transformers = { git = "https://github.com/huggingface/candle", package = "candle-transformers", default-features = false }

# Tokenizers: Regex-Backend einschalten
tokenizers = { version = "0.22", default-features = false,features = ["fancy-regex"] }

# Sonstige
ahash              = "0.8"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"

#llm = { version = "1.3.6", default-features = false}
rand = "0.9.2"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0.146"
safetensors = "0.7.0"

# ğŸ‘‰ Falls du spÃ¤ter GPU nutzen willst:
#   candle-core = { git = "...", package = "candle-core", features = ["cuda"] }
#   candle-nn   = { git = "...", features = ["cuda"] }
